spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      port: 35729

server:
  port: 8082
  servlet:
    context-path: /lsso-client

logging:
  level:
    org.springframework: INFO

resourceserver:
  api:
    project:
      url: http://localhost:8081/lsso-resource-server/api/projects
        