server:
  port: 8081
  servlet:
    context-path: /lsso-resource-server

####### resource server configuration properties
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  devtools:
    livereload:
      port: 35730

oauth:
  auth-servers:
    baeldung:
      jwk-set-url: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
      issuer-uri: http://localhost:8083/auth/realms/baeldung
    tenant2:
      jwk-set-url: http://localhost:8084/auth/realms/tenant2/protocol/openid-connect/certs
      issuer-uri: http://localhost:8084/auth/realms/tenant2

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
